### PR TITLE
some features i worked on

### PR DESCRIPTION
**Pull request by visit1985**
Hi @xtfxme

First of all: Thanks for this awesome script!
I played with it for some weeks now and wanna share my outcome.
Please don't be scared, I've rewritten a pretty huge part of the script to use btrfs subvolume set-default to mark the subvolume to boot.
I also tried to implement all your FIXME's.

I would appreciate it, if you find some time to have a look on it and tell me your thoughts.

Thanks,
@visit1985

### CODE REVIEW

**Comment by anthonyrisinger** [comment]
awesome! 95% of this LGTM, with only a couple minor changes i will detail ASAP... i just got married last weekend, and moved to a new home just 2 days ago, so i'm a wee bit busy ATM, but i should be able to give you real feedback before next week.

**Comment by visit1985** [comment]
My sincere congrats! No need to rush. I'm in vacation until Sept. 19th and probably offline until then. Take care on your wife instead. That's more important ;)

**Comment by visit1985** [comment]
Can you please detail the "minor changes" you mentioned? I'm planing to implement auto-mounting of degraded raid volumes, which is the only major feature missing, I think. While doing that, I can take care of these fixes, to get this up to the AUR asap.

**Comment by anthonyrisinger** [comment]
they are not important enough to worry about... merged; btw, if you'll be working on more issues/features, i don't have a problem adding you to the repository so you can commit and/or handle pull reqs without me. when life stops eating my time i'll be more in the game, but that time is not now.

**Comment by anthonyrisinger** [comment]
i don't like setting the default subvolume much, because in the past it's been flaky and i think the mount option is safer/clearer, but we'll try it out

**Comment by triplem** [comment]
I agree with xtfxme. I do find it more KISS to declare the subvolume directly in the fstab.

**Comment by visit1985** [comment]
@xtfxme: I found it more simple and clear for the non-expert user to not bother with mount options. I use this for 4 month now and never had a problem with setting the default subvol.

@triplem: The fstab is not in use at this early stage of boot. The only params which take effect are the kernel boot options from Grub or Syslinux. Also the subvol option in fstab can be misleading, when you boot from __rollback. When I started working with btrfs, I had problems on auto-generating the grub.conf from fstab, that's why I decided to keep it as simple as possible.

**Comment by visit1985** [comment]
@xtfxme: Ahh yes... I would appreciate adding me to the repo. I can also work on the new features in a different branch.

**Comment by anthonyrisinger** [comment]
@visit1985 that's fine i'll go ahead and add you; except for simple bugfixes, i would appreciate it if you would still work out of your own github repos, and still open pull requests, even if you expect to merge it yourself... it's a good habit to have and it leaves a clear trail.

CLOSED :)

**Pull request merged**
